[licenses]
allow = ["MIT", "Apache-2.0"]
copyleft = "deny"
confidence-threshold = 1.0

exceptions = [
    { allow = ["ISC"], name = "inotify-sys", version = "*" },
    { allow = ["ISC"], name = "inotify", version = "*" },
    { allow = ["CC0-1.0"], name = "notify", version = "*" },
    { allow = ["BSD-3-Clause"], name = "fuchsia-zircon", version = "*" },
    { allow = ["BSD-3-Clause"], name = "fuchsia-zircon-sys", version = "*" },
    { allow = ["BSD-3-Clause"], name = "instant", version = "*" },
    { allow = ["CC0-1.0"], name = "dunce", version = "*" },
]

[bans]
multiple-versions = "deny"
wildcards = "warn"

[sources]
unknown-git = "deny"
