[package]
name = "atelier-cli"
version = "0.1.0"
authors = ["Karl Bergström <karl.anton.bergstrom@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
capnp = "0.14.0"
capnp-rpc = "0.14.0"
tokio = { version = "1.0.2", features = ["io-std", "rt", "net", "io-util"] }
tokio-util = { version = "0.6.1", features = ["codec", "compat"] }
futures = { version = "0.3.12", default-features = false, features = ["std", "async-await"] }
atelier-schema = { path = "../schema" }
uuid = "0.8.2"
async-trait = "0.1.22"
crossterm = { version = "0.17", features = ["event-stream"] }
defer = "0.1.0"
tokio-stream = { version = "0.1.2", features = ["io-util"] }
