[package]
name = "atelier-core"
version = "0.1.0"
edition = "2018"

[features]
serde-1 = ["serde"]

[dependencies]
uuid = "0.7"
proc-macro-hack = "0.5"
serde = { version = "1.0", optional = true, features = ["derive"] }
asset-uuid = { path = "./asset-uuid" }

[dev-dependencies]
serde_json = "1.0"
bincode = "1.2"
