[package]
name = "atelier-daemon"
version = "0.1.0"
edition = "2018"

[dependencies]
atelier-core = { path = "../core" }
atelier-schema = { path = "../schema" }
atelier-importer = { path = "../importer" }
dunce = "1.0"
path-clean = "0.1"
path-slash = "0.1.1"
capnp = { version = "0.10.0" }
capnp-rpc = "0.10.0"
notify = "4.0.0"
lmdb = { git = "http://github.com/kabergstrom/lmdb-rs" }
rayon = "1.2"
fern = "0.5"
log = { version = "0.4", features = ["serde"] }
tokio = "0.1"
futures = "0.1"
owning_ref = "0.4"
crossbeam-channel = "0.3"
mopa = "0.2.2"
serde = "1.0"
serde_derive = "1.0"
erased-serde = "0.3"
bincode = "1.1"
ron = "0.5"
meowhash = "0.1.2"
scoped_threadpool = "0.1.9"
num_cpus = "1.10"
smush = { version = "0.1", default-features = false, features = [ "lz4_support" ], optional = true }

[dev-dependencies]
tempfile = "3"

[features]
compression = [ "smush" ]