name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  RUSTFLAGS: -Cdebuginfo=0 -Dwarnings
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    name: Lint and Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true

      - run: rustup component add rustfmt
        if: matrix.toolchain == 'nightly' && matrix.os == 'ubuntu-latest'

      - run: cargo +nightly fmt --all -- --check
        if: matrix.toolchain == 'nightly' && matrix.os == 'ubuntu-latest'
        
      # FIXME: clippy crashing on nightly
      - run: rustup component add clippy
        if: matrix.toolchain == 'stable' && matrix.os == 'ubuntu-latest'

      - run: cargo +stable clippy -Z unstable-options --workspace --all-targets --all-features
        if: matrix.toolchain == 'stable' && matrix.os == 'ubuntu-latest'

      - run: cargo test --workspace --all-features -- --nocapture
